version: "2"
services:
    bot:
        build: ./bot
        depends_on:
            - db            
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
